name: isbn_searcher
description: ISBN lookup library for Dart and Flutter using Google Books and isbnsearch.org.
version: 1.0.3
homepage: https://github.com/berkbb/isbn_searcher
repository: https://github.com/berkbb/isbn_searcher
issue_tracker: https://github.com/berkbb/isbn_searcher/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.2.2
  html: ^0.15.4
  logbox_color: ^1.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
